Bundle "brookhong/DBGPavim"
Bundle "evidens/vim-twig.git"
Bundle 'slim-template/vim-slim.git'
Bundle 'burnettk/vim-angular'
Bundle 'editorconfig/editorconfig-vim'
Bundle 'Shougo/vimproc'
Bundle 'Quramy/tsuquyomi'
Bundle 'leafgarland/typescript-vim'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'valloric/youcompleteme'
Plugin 'w0rp/ale'
Plugin 'octref/RootIgnore'
