Bundle "brookhong/DBGPavim"
Bundle "ervandew/supertab.git"
Bundle "evidens/vim-twig.git"
Bundle 'slim-template/vim-slim.git'
Bundle 'burnettk/vim-angular'
Bundle 'editorconfig/editorconfig-vim'
Bundle 'Shougo/vimproc'
Bundle 'Quramy/tsuquyomi'
Bundle 'leafgarland/typescript-vim'
